### ISSUE TITLE
use in zikichombo.org

### ISSUE THREAD

**Issue by wsc1** [jfreymuth/vorbis#6]
Hi,

Nice work on the vorbis package!

I did not see another way to contact you, or I'd have done so outside the issue tracker.  Nonetheless, on behalf of http://zikichombo.org, we're looking for pure Go encoders and decoders.

Thus want to know if you'd be open to either a PR integrating zikichombo.org support for ogg/vorbis or contributing/having your decoder contributed to zikichombo.org/codec (under shared author BSD license).

Thanks
Scott

**Comment by jfreymuth** [comment]
If I understand correctly, there are three ways to make this happen:
1. Change the API of this package to implement interfaces defined in zikichombo/codec
I would prefer not to do this for various reasons, among others this would introduce a dependency to this package.
2. Create a wrapper that imports this package
This is probably the easiest way to quickly add ogg/vorbis support to zikichombo, but it would also mean zikichombo will depend on this package. (I am open to changing the license; adding support for go modules is planned anyway)
3. Writing a new decoder for zikichombo
I am willing to do this, since it will mostly be copying things from here, but it will lead to the project existing in two places and being harder to maintain.

Let me know what you think and if I am misunderstanding anything.

Btw, when I write "this package", I mostly mean [jfreymuth/oggvorbis](https://github.com/jfreymuth/oggvorbis) since that is the package for dealing with the .ogg file format. This package only exists to make it possible to decode vorbis audio from different container formats.

**Comment by wsc1** [comment]
Regarding ways to make this happen, we're improvising at this point, there may be other ideas such as submodule https://blog.github.com/2016-02-01-working-with-submodules/, although I personally tend to stay away from them because the whole idea of git submodules goes against the grain of everything else in git.

For 
1. Changing the API of jfreymuth/oggvorbis,  we would be interested to know what zc can do to make importing it as easy and inviting as possible, independent of whether or not jfreymuth/oggvorbis would actually import zc, as this decision clearly is outside the scope of zc.  For implementing the sound.{Source,Sink,...} interfaces, the only zc import dependency for the interfaces is zikichombo.org/sound/freq, which we like a lot and is pretty stable.  W.R.T licensing overhead associated with imports, we're trying to be as practical as possible, which at this point for us means we're open to ideas but will likely be quite conservative about proceeding so that zc consumers and potential consumers have a very simple reliable notion of licensing.

2. Creating a wrapper somewhere sounds good.  For zc importing jfreymuth/oggvorbis, we're in principle very open to that but in practice very much improvising around the licensing issues mentioned in 1 above.    As this sort of non-code thing may evolve more slowly than actually coding a wrapper, maybe we could do that somewhere that imports both zc and jfreymuth/oggvorbis to serve as a point of reference as import direction/maintenance gets worked out.  For example, either you or I could create a fork somewhere and collaborate on it.

3. We'd be honoured for any code you'd want to write for zc.  We require only an out-of-githhub band statement (such as email) agreeing to participate as an author in the shared author BSD license.  For overhead associated with duplication of the project, we are happy to do our best to alleviate that and address any maintenance overhead we can on our end. Although we are  not curerntly in a position to be able to guarantee someone could actually track jfreymuth/oggvorbis changes and proactively deal with resulting zc/codec/oggvorbis changes,   we can at least state we would try, and using go modules +semver would likely take care of most of it.

Sorry I created an issue  to the wrong package for ogg/vorbis support, although vorbis encoding may end up in other containers in zc as well.

**Comment by wsc1** [comment]
As a minor update, I've thought of making an "ext" repository under the ZikiChombo organisation which would import both zc and whatever packages from /jfreymuth and make a wrapper.  Thoughts?

**Comment by jfreymuth** [comment]
Closing this, since a wrapper now exists in zikichombo/ext.

**Comment by wsc1** [comment]
Thanks for the wrapper in ext.

There is now a proposed zc collective licensing mechanism [here](https://github.com/zikichombo/meta/issues/6) which would allow importing in zc directly.

If you are interested, please let us know what you think.
